### ISSUE TITLE
conn_sb generates q instead of p

### ISSUE THREAD

**Issue by dmarmsoler** [habtom/factum#31]
the first "pbpnt (pbcmp q c)" after the second implication should be "pbpnt (pbcmp p c)".
So p instead of q

**Comment by habtom** [comment]
conn(q.pnt,s.snt)

**Comment by habtom** [comment]
conn_sb: G(cAct(p) ∧ val(p.psb, Subscription.sub(s.id,e)) 
			⇒((cAct(s) ∧ cAct(p) ∧ e = Event.evt(p.pnt) ⇒ conn(q.pnt,s.snt)) 
				W val(p.psb, Subscription.unsub(s.id,e))))

**Comment by habtom** [comment]
The error comes from the formula, not the code, now changed
