### ISSUE TITLE
Problem Generating Pattern.xtext artifacts

### ISSUE THREAD

**Issue by Ten10** [habtom/factum#73]
Getting the following error both in Ubuntu and Windows when trying to generate the Pattern.xtext artifacts:
[log.txt](https://github.com/habtom/factum/files/3072354/log.txt)

Would appreciate any help that you can provide.

Thanks in advance,
Jonathan

**Comment by Ten10** [comment]
Correction it looks like the elements are already generated so I could start the factum ide but only in Windows.
It fails to start on Ubuntu.

**Comment by dmarmsoler** [comment]
Hi Jonathan,

could you please provide as with some details about the steps you followed to setup your environment?
We are currently working on a better documentation to setup the environment.
For development I recommend the following steps:

1. Download Obeo designer
2. Create a new Xtext project called org.tum.factum.pattern (be sure to set extension name to "pmodel")
3. Ensure the encoding is set to UTF-8 in the mwe2 file.
4. Copy Pattern.xtext (from the repository) to org.tum.factum.pattern
5. Run generate XText artifacts on pattern.xtext
6. Copy folders formatting2, generator, scoping, and validation from the repository to the workspace
7. Launch org.tum.factum.pattern

Let us know if this works or if you are still having problems.

**Comment by Ten10** [comment]
I think the issue is because I used jdk-11.
https://github.com/eclipse/xtext/issues/1316

Will try to install a lower jdk and report the results here.
Thanks!

**Comment by Ten10** [comment]
I ended up installing a newer version of the xtext plugin which supports jdk 11.(2.17.1)
I managed to generate the artifacts.
Thanks for all of your help.
